const state={mailbox:[],view:"overview",connected:false};
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const toast=$("#toast"),content=$("#content"),title=$("#title"),connect=$("#connectBtn");

function notify(msg){if(!toast)return;toast.textContent=msg;toast.classList.add("show");clearTimeout(window._toast);window._toast=setTimeout(()=>toast.classList.remove("show"),2800)}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function riskClass(r){return r==="High"?"high":""}
function selected(){return $$(".rpm-select:checked").map(x=>x.dataset.id)}
function avatar(m){return esc(((m?.from?.emailAddress?.name||m?.from?.emailAddress?.address||"??").slice(0,2)).toUpperCase())}
function rows(items){return items.map(m=>`<div class="rpmRow"><input class="rpm-select" type="checkbox" data-id="${esc(m.id)}"><div class="rpmAvatar">${avatar(m)}</div><div class="rpmMeta"><strong>${esc(m.from?.emailAddress?.name||m.from?.emailAddress?.address||"Unknown sender")}</strong><small>${esc(m.subject||"(no subject)")}</small><span>${esc(m.reason||new Date(m.receivedDateTime).toLocaleString())}</span></div><b class="risk ${riskClass(m.risk)}">${esc(m.risk||"Low")}</b></div>`).join("")||'<div class="empty">Nothing to review.</div>'}
function toolbar(items){return '<div class="rpmToolbar">'+items.map(x=>'<button class="'+(x.danger?"rpmDanger":"rpmSoft")+'" data-action="'+x.action+'">'+x.label+'</button>').join("")+"</div>"}
function wireActions(){ $$(".rpmToolbar [data-action]").forEach(b=>b.onclick=()=>runAction(b.dataset.action,selected())); $$(".rpm-select").forEach(c=>c.onchange=()=>{const n=selected().length;const el=$("#selectedCount");if(el)el.textContent=n})}
async function runAction(action,ids){if(!ids.length)return notify("Select at least one message.");try{let payload={action,messageIds:ids};if(action==="blockSender")payload.senders=[...new Set(ids.map(id=>state.mailbox.find(m=>m.id===id)?.from?.emailAddress?.address).filter(Boolean))];const r=await fetch("/api/mail/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error||"Action failed.");if(action==="blockSender")notify((d.blocked?.length||0)+" sender(s) blocked in Outlook.");else{const ok=(d.results||[]).filter(x=>x.ok).length;notify(ok+" message"+(ok===1?"":"s")+" updated.");}await loadInbox(false);renderView()}catch(e){notify(e.message)}}
async function loadInbox(show=true){try{const r=await fetch("/api/mail/inbox?top=100");const d=await r.json();if(!r.ok)throw Error(d.error||"Could not load Outlook.");state.mailbox=d.messages||[];state.connected=true;$("#connectionState").textContent=d.user?.mail||d.user?.userPrincipalName||"Connected";connect.textContent="Outlook connected";if(show)notify(`Scanned ${state.mailbox.length} messages.`);renderView()}catch(e){if(show)notify(e.message)}}
function overview(){const m=state.mailbox,high=m.filter(x=>x.risk==="High").length,review=m.filter(x=>x.risk==="Review").length,unread=m.filter(x=>!x.isRead).length,att=m.filter(x=>x.hasAttachments).length;content.innerHTML=`<div class="hero"><div><span class="status">● Protected mode</span><h2>Your Outlook, under control.</h2><p>Scan your inbox, identify risky mail and clean clutter without silently deleting anything.</p><button class="primary" id="startBtn">Scan & review</button></div><div class="heroMetric"><span>Current scan</span><strong>${m.length}</strong><small>messages loaded</small></div></div><div class="metrics"><article><span>High risk</span><strong>${high}</strong><small>requires review</small></article><article><span>Promotions</span><strong>${review}</strong><small>newsletters & bulk mail</small></article><article><span>Unread</span><strong>${unread}</strong><small>in current scan</small></article><article><span>Attachments</span><strong>${att}</strong><small>messages with files</small></article></div><div class="grid"><section class="panel"><div class="panelHead"><div><h3>Priority review</h3><p>Risky messages detected in your inbox</p></div><button class="textBtn" data-go="spam">View all</button></div>${rows(m.filter(x=>x.risk==="High"||x.risk==="Review").slice(0,6))}</section><section class="panel"><div class="panelHead"><div><h3>Quick cleanup</h3><p>Choose what you want to review</p></div></div><div class="quick"><button data-go="inbox"><span>▣</span><div><strong>Inbox cleanup</strong><small>Search and bulk-manage messages</small></div><em>Open →</em></button><button data-go="spam"><span>⚠</span><div><strong>Spam & phishing</strong><small>Review suspicious messages</small></div><em>Review →</em></button><button data-go="newsletters"><span>✉</span><div><strong>Newsletters</strong><small>Find promotional mail</small></div><em>Review →</em></button><button data-go="senders"><span>◎</span><div><strong>Senders</strong><small>See who sends the most mail</small></div><em>Review →</em></button></div></section></div><div class="security"><div><span class="shield">✓</span><div><strong>Protected cleanup</strong><p>Actions are explicit and selected messages are shown before changes are made.</p></div><span class="secureBadge">SAFE BY DEFAULT</span></div></div>`;$("#startBtn").onclick=()=>loadInbox(true);$$("[data-go]").forEach(b=>b.onclick=()=>navigate(b.dataset.go))}
function inbox(){const all=state.mailbox;content.innerHTML='<div class="tablePanel"><div class="panelHead"><div><h3>Inbox cleanup</h3><p>Search, filter and manage Outlook messages.</p></div><span id="selectedCount">0</span></div><div class="toolbar"><input id="rpmSearch" class="search" placeholder="Search sender, subject or content"><select id="rpmRisk" class="select"><option value="">All risk levels</option><option>High</option><option>Review</option><option>Low</option></select><select id="rpmRead" class="select"><option value="">All read status</option><option value="unread">Unread</option><option value="read">Read</option></select></div>'+toolbar([{label:"Archive",action:"archive"},{label:"Mark read",action:"markRead"},{label:"Mark unread",action:"markUnread"},{label:"Quarantine",action:"quarantine",danger:true},{label:"Delete",action:"delete",danger:true},{label:"Block sender",action:"blockSender",danger:true}])+'<div id="rpmRows" class="rpmRows"></div></div>';const draw=()=>{const q=($("#rpmSearch").value||"").toLowerCase(),risk=$("#rpmRisk").value,read=$("#rpmRead").value;const a=all.filter(m=>(!q||JSON.stringify(m).toLowerCase().includes(q))&&(!risk||m.risk===risk)&&(!read||(read==="unread"&&!m.isRead)||(read==="read"&&m.isRead)));$("#rpmRows").innerHTML=rows(a);wireActions()};$("#rpmSearch").oninput=draw;$("#rpmRisk").onchange=draw;$("#rpmRead").onchange=draw;draw()}
function spam(){const a=state.mailbox.filter(m=>m.risk==="High");content.innerHTML='<div class="tablePanel"><div class="panelHead"><div><h3>Spam & phishing</h3><p>Review suspicious messages before deleting or blocking.</p></div><span class="risk high">'+a.length+' flagged</span></div>'+toolbar([{label:"Quarantine",action:"quarantine",danger:true},{label:"Delete",action:"delete",danger:true},{label:"Block sender",action:"blockSender",danger:true},{label:"Archive",action:"archive"}])+'<div class="rpmRows">'+rows(a)+'</div></div>';wireActions()}
function newsletters(){const a=state.mailbox.filter(m=>m.risk==="Review");content.innerHTML=`<div class="tablePanel"><div class="panelHead"><div><h3>Newsletters & promotions</h3><p>Bulk mail detected from your current inbox scan.</p></div><span>${a.length} found</span></div>${toolbar([{label:"Archive selected",action:"archive"},{label:"Mark read",action:"markRead"}])}<div class="rpmRows">${rows(a)}</div></div>`;wireActions()}
function senders(){const map={};state.mailbox.forEach(m=>{const e=m.from?.emailAddress?.address||"unknown";map[e]=(map[e]||0)+1});const a=Object.entries(map).sort((x,y)=>y[1]-x[1]);content.innerHTML=`<div class="tablePanel"><div class="panelHead"><div><h3>Sender management</h3><p>Frequent senders from the current scan.</p></div></div><div class="rpmRows">${a.map(([e,n])=>`<div class="rpmSender"><div class="rpmAvatar">@</div><div><strong>${esc(e)}</strong><small>${n} message${n===1?"":"s"}</small></div><button class="rpmSoft" data-sender="${esc(e)}">Review</button></div>`).join("")||'<div class="empty">Scan your inbox first.</div>'}</div></div>`;$$("[data-sender]").forEach(b=>b.onclick=()=>notify("Sender controls: review, archive, or block can be added here."))}
function rules(){content.innerHTML=`<div class="tablePanel"><div class="panelHead"><div><h3>Smart Rules</h3><p>Rules are shown here before we make them automatic.</p></div><button class="primary" id="newRule">New rule</button></div><div class="rpmRule"><div><strong>Quarantine high-risk messages</strong><small>Phishing signals → RPMailClean quarantine</small></div><button class="rpmSwitch on" data-rule></button></div><div class="rpmRule"><div><strong>Review newsletters</strong><small>Promotional mail → review queue</small></div><button class="rpmSwitch on" data-rule></button></div><div class="rpmRule"><div><strong>Flag attachment-heavy mail</strong><small>Messages with attachments → review</small></div><button class="rpmSwitch" data-rule></button></div><div class="rpmRule"><div><strong>Stale mail</strong><small>Older mail → review queue</small></div><button class="rpmSwitch" data-rule></button></div></div>`;$$("[data-rule]").forEach(b=>b.onclick=()=>b.classList.toggle("on"));$("#newRule").onclick=()=>notify("Rule builder is ready for the next step.")}
function analytics(){const m=state.mailbox;content.innerHTML=`<div class="statGrid"><div class="stat"><span>Scanned</span><strong>${m.length}</strong></div><div class="stat"><span>High risk</span><strong>${m.filter(x=>x.risk==="High").length}</strong></div><div class="stat"><span>Promotional</span><strong>${m.filter(x=>x.risk==="Review").length}</strong></div><div class="stat"><span>Unread</span><strong>${m.filter(x=>!x.isRead).length}</strong></div><div class="stat"><span>Attachments</span><strong>${m.filter(x=>x.hasAttachments).length}</strong></div><div class="stat"><span>Senders</span><strong>${new Set(m.map(x=>x.from?.emailAddress?.address).filter(Boolean)).size}</strong></div></div><div class="tablePanel"><div class="panelHead"><div><h3>What this scan tells you</h3><p>Statistics are based only on messages currently loaded from Outlook.</p></div></div><p class="rpmSub">No permanent analytics database is used yet. This keeps the first version lightweight and privacy-focused.</p></div>`}
function settings(){content.innerHTML=`<div class="tablePanel"><div class="panelHead"><div><h3>Settings</h3><p>RPMailClean preferences and connection status.</p></div></div><div class="rpmRule"><div><strong>Protected mode</strong><small>Never perform bulk changes without a selected action.</small></div><span class="secureBadge">ON</span></div><div class="rpmRule"><div><strong>Risk detection</strong><small>Heuristic screening of subject, preview and sender address.</small></div><span class="secureBadge">ON</span></div><div class="rpmRule"><div><strong>Outlook connection</strong><small>${state.connected?"Connected":"Not connected"}</small></div><button class="rpmSoft" id="settingsScan">Test connection</button></div></div>`;$("#settingsScan").onclick=()=>loadInbox(true)}
function navigate(v){state.view=v;$$(".nav").forEach(n=>n.classList.toggle("active",n.dataset.view===v));title.textContent={overview:"Inbox overview",inbox:"Inbox cleanup",spam:"Spam & Phishing",newsletters:"Newsletters",senders:"Sender management",rules:"Smart Rules",analytics:"Analytics",settings:"Settings"}[v]||"RPMailClean";renderView()}
function renderView(){({overview,inbox,spam,newsletters,senders,rules,analytics,settings}[state.view]||overview)()}
async function init(){connect.onclick=e=>{e.preventDefault();location.href="/api/auth/login"};$$(".nav[data-view]").forEach(n=>n.onclick=e=>{e.preventDefault();navigate(n.dataset.view)});$$("[data-action]").forEach(b=>b.onclick=()=>notify("Connect Outlook first to use cleanup actions."));try{const r=await fetch("/api/auth/status");const d=await r.json();if(d.connected){state.connected=true;connect.textContent="Outlook connected";$("#connectionState").textContent=d.user?.mail||d.user?.userPrincipalName||"Connected";await loadInbox(false)}}catch{}renderView()}
document.addEventListener("DOMContentLoaded",init);